version: '3.8'

services:
  mysql:
    image: mysql:8.0   # Use the desired MySQL version
    container_name: mysql_container
    restart: always    # Ensures the container restarts on failure
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # Replace with a secure password
      MYSQL_DATABASE: exampledb           # Optional: Pre-create a database
      MYSQL_USER: exampleuser             # Optional: Create a user
      MYSQL_PASSWORD: examplepassword     # Optional: Set a password for the user
    ports:
      - "3306:3306"   # Map MySQL port to the host
    volumes:
      - db_data:/var/lib/mysql    # Persist data across container restarts

volumes:
  db_data:
